<Project>
  <PropertyGroup>
    <Product>Bluehill.Hangul</Product>
    <PackageProjectUrl>https://hangul.bluehill.dev</PackageProjectUrl>
    <PackageTags>hangul;josa;한글;조사;bluehill</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/BluehillNuGet/Bluehill.Hangul</RepositoryUrl>
    <AssemblyVersion>2</AssemblyVersion>
    <FileVersion>2.1.3</FileVersion>
    <Version>2.1.3</Version>
  </PropertyGroup>
</Project>