<Project Sdk="Microsoft.NET.Sdk.Razor">
  <Sdk Name="Bluehill.MSBuild.Sdk" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <NoWarn>$(NoWarn);SA1600</NoWarn>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Bluehill.Hangul.Pages.Pages" />
    <Using Include="Bunit" />
    <Using Include="Bunit.TestDoubles" />
    <Using Include="Microsoft.Extensions.DependencyInjection" />
    <Using Include="Microsoft.Extensions.Localization" />
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Bluehill.Hangul.Pages\Bluehill.Hangul.Pages.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="bunit" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      </PackageReference>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
</Project>